
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookstore?useUnicode=true&characterEncoding=UTF-8
    data-username: test
    data-password: yygucailiang
    username: test
    password: yygucailiang
  jpa:
    show-sql: true
